# Copyright (c) 2024, Trail of Bits, Inc.

#
# Parser data sources
#

# char * fgets(char * restrict str, int size, FILE * restrict stream);
- function: fgets
  model:
    return_type: data
    arguments:
      - data    # char * restrict str
      - nodata  # int size
      - nodata  # FILE * restrict stream
    category: source

# char * gets(char * str);
- function: gets
  model:
    return_type: data
    arguments:
      - data    # char * str
    category: source

# char * gets_s(char * str, rsize_t n);
- function: gets_s
  model:
    return_type: data
    arguments:
      - data    # char * str
      - nodata  # rsize_t n
    category: source

# int getchar(void);
- function: getchar
  model:
    return_type: data
    arguments: []
    category: source

# int scanf(const char * restrict format, ...);
- function: scanf
  model:
    return_type: nodata
    arguments:
      - nodata  # const char * restrict format
      - data    # ...
    category: source
