# Copyright (c) 2024, Trail of Bits, Inc.

sink:
  - printf
  - fprintf
  - perror
  - exit

source:
  - getchar
  - scanf
  - fgets

parse:
  - isspace
  - isdigit

noparse:
  - fopen
  - fclose
  - malloc
  - free
