site_name: "VAST: MLIR for Program Analysis"
repo_url: https://github.com/trailofbits/vast
nav:
  - Introduction: README.md
  - Getting Started:
    - Build & Run: GettingStarted/build.md
    - Debug: GettingStarted/debug.md
    - How to contribute: CONTRIBUTING.md
    - How to create a new dialect: GettingStarted/extend.md
    - Driver integration: GettingStarted/integration.md
  - Dialects:
    - ABI: dialects/ABI/ABI.md
    - Core: dialects/Core/Core.md
    - High Level: dialects/HighLevel/HighLevel.md
    - Low Level: dialects/LowLevel/LowLevel.md
    - Meta: dialects/Meta/Meta.md
    - Unsupported: dialects/Unsupported/Unsupported.md
  - Passes:
    - High Level: dialects/HighLevelPasses.md
    - Low Level: dialects/LowLevelPasses.md
  - Tools:
    - Compiler Driver: Tools/vast-front.md
    - LSP Server: Tools/vast-lsp-server.md
    - Optimizer: Tools/vast-opt.md
    - Query: Tools/vast-query.md
    - REPL: Tools/vast-repl.md
  - Related Projects: Projects/related.md
  - Benchmarks:
    - LLVM Single Source: Benchmarks/single-source-results.md
    - SV-Comp: Benchmarks/sv-comp-results.md
    - Linux Kernel: Benchmarks/linux_kernel_times.md
  - About:
    - 'License': 'statement.md'

theme:
  name: material
  language: en
  custom_dir: assets
  favicon: img/favicon.ico
  logo: img/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: pink

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: pink

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: pink

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/slack
      link: https://slack.empirehacking.nyc/

  copyright: Copyright &copy; 2023 Trail of Bits
