// RUN: %vast-front -vast-emit-mlir=hl %s -o - | %file-check %s
// RUN: %vast-front -vast-emit-mlir=hl %s -o %t && %vast-opt %t | diff -B %t -

// CHECK-DAG: hl.func @cacosf
// CHECK-DAG: hl.func @cacos
// CHECK-DAG: hl.func @cacosl
// CHECK-DAG: hl.func @casinf
// CHECK-DAG: hl.func @casin
// CHECK-DAG: hl.func @casinl
// CHECK-DAG: hl.func @catanf
// CHECK-DAG: hl.func @catan
// CHECK-DAG: hl.func @catanl
// CHECK-DAG: hl.func @ccosf
// CHECK-DAG: hl.func @ccos
// CHECK-DAG: hl.func @ccosl
// CHECK-DAG: hl.func @csinf
// CHECK-DAG: hl.func @csin
// CHECK-DAG: hl.func @csinl
// CHECK-DAG: hl.func @ctanf
// CHECK-DAG: hl.func @ctan
// CHECK-DAG: hl.func @ctanl
// CHECK-DAG: hl.func @cacoshf
// CHECK-DAG: hl.func @cacosh
// CHECK-DAG: hl.func @cacoshl
// CHECK-DAG: hl.func @casinhf
// CHECK-DAG: hl.func @casinh
// CHECK-DAG: hl.func @casinhl
// CHECK-DAG: hl.func @catanhf
// CHECK-DAG: hl.func @catanh
// CHECK-DAG: hl.func @catanhl
// CHECK-DAG: hl.func @ccoshf
// CHECK-DAG: hl.func @ccosh
// CHECK-DAG: hl.func @ccoshl
// CHECK-DAG: hl.func @csinhf
// CHECK-DAG: hl.func @csinh
// CHECK-DAG: hl.func @csinhl
// CHECK-DAG: hl.func @ctanhf
// CHECK-DAG: hl.func @ctanh
// CHECK-DAG: hl.func @ctanhl
// CHECK-DAG: hl.func @cexpf
// CHECK-DAG: hl.func @cexp
// CHECK-DAG: hl.func @cexpl
// CHECK-DAG: hl.func @clogf
// CHECK-DAG: hl.func @clog
// CHECK-DAG: hl.func @clogl
// CHECK-DAG: hl.func @cabsf
// CHECK-DAG: hl.func @cabs
// CHECK-DAG: hl.func @cabsl
// CHECK-DAG: hl.func @cpowf
// CHECK-DAG: hl.func @cpow
// CHECK-DAG: hl.func @cpowl
// CHECK-DAG: hl.func @csqrtf
// CHECK-DAG: hl.func @csqrt
// CHECK-DAG: hl.func @csqrtl
// CHECK-DAG: hl.func @cargf
// CHECK-DAG: hl.func @carg
// CHECK-DAG: hl.func @cargl
// CHECK-DAG: hl.func @cimagf
// CHECK-DAG: hl.func @cimag
// CHECK-DAG: hl.func @cimagl
// CHECK-DAG: hl.func @conjf
// CHECK-DAG: hl.func @conj
// CHECK-DAG: hl.func @conjl
// CHECK-DAG: hl.func @cprojf
// CHECK-DAG: hl.func @cproj
// CHECK-DAG: hl.func @cprojl
// CHECK-DAG: hl.func @crealf
// CHECK-DAG: hl.func @creal
// CHECK-DAG: hl.func @creall

#include <complex.h>