// RUN: %vast-front -vast-emit-mlir=hl %s -o - | %file-check %s
// RUN: %vast-front -vast-emit-mlir=hl %s -o %t && %vast-opt %t | diff -B %t -

// CHECK: hl.func @cacosf
// CHECK: hl.func @cacos
// CHECK: hl.func @cacosl
// CHECK: hl.func @casinf
// CHECK: hl.func @casin
// CHECK: hl.func @casinl
// CHECK: hl.func @catanf
// CHECK: hl.func @catan
// CHECK: hl.func @catanl
// CHECK: hl.func @ccosf
// CHECK: hl.func @ccos
// CHECK: hl.func @ccosl
// CHECK: hl.func @csinf
// CHECK: hl.func @csin
// CHECK: hl.func @csinl
// CHECK: hl.func @ctanf
// CHECK: hl.func @ctan
// CHECK: hl.func @ctanl
// CHECK: hl.func @cacoshf
// CHECK: hl.func @cacosh
// CHECK: hl.func @cacoshl
// CHECK: hl.func @casinhf
// CHECK: hl.func @casinh
// CHECK: hl.func @casinhl
// CHECK: hl.func @catanhf
// CHECK: hl.func @catanh
// CHECK: hl.func @catanhl
// CHECK: hl.func @ccoshf
// CHECK: hl.func @ccosh
// CHECK: hl.func @ccoshl
// CHECK: hl.func @csinhf
// CHECK: hl.func @csinh
// CHECK: hl.func @csinhl
// CHECK: hl.func @ctanhf
// CHECK: hl.func @ctanh
// CHECK: hl.func @ctanhl
// CHECK: hl.func @cexpf
// CHECK: hl.func @cexp
// CHECK: hl.func @cexpl
// CHECK: hl.func @clogf
// CHECK: hl.func @clog
// CHECK: hl.func @clogl
// CHECK: hl.func @cabsf
// CHECK: hl.func @cabs
// CHECK: hl.func @cabsl
// CHECK: hl.func @cpowf
// CHECK: hl.func @cpow
// CHECK: hl.func @cpowl
// CHECK: hl.func @csqrtf
// CHECK: hl.func @csqrt
// CHECK: hl.func @csqrtl
// CHECK: hl.func @cargf
// CHECK: hl.func @carg
// CHECK: hl.func @cargl
// CHECK: hl.func @cimagf
// CHECK: hl.func @cimag
// CHECK: hl.func @cimagl
// CHECK: hl.func @conjf
// CHECK: hl.func @conj
// CHECK: hl.func @conjl
// CHECK: hl.func @cprojf
// CHECK: hl.func @cproj
// CHECK: hl.func @cprojl
// CHECK: hl.func @crealf
// CHECK: hl.func @creal
// CHECK: hl.func @creall

#include <complex.h>