#
# Copyright (c) 2021-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Build-Test-Release

on:
  push:
    branches:
      - 'master'
      - 'visitor-api'

    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: 'ubuntu',
          os: ubuntu-20.04,
          arch: 'x86_64',
          llvm_pkg: 'x86_64-linux-gnu-ubuntu-18.04',
        }

        - {
          name: 'macos',
          os: macos-11,
          arch: 'x86_64',
          llvm_pkg: 'x86_64-apple-darwin'
        }
        llvm: [ '13.0.1' ]

    timeout-minutes: 20

    steps:
      - name: Setup the build paths
        shell: bash
        id: build_paths
        run: |
          build_path="build"
          source_path="src"
          install_path="install"
          downloads_path="downloads"
          ccache_path="ccache"
          package_path="package"

          mkdir -p ${source_path} \
            ${install_path} \
            ${build_path} \
            ${downloads_path} \
            ${ccache_path}

          echo ::set-output name=source::$(pwd)/${source_path}
          echo ::set-output name=install::$(pwd)/${install_path}
          echo ::set-output name=build::$(pwd)/${build_path}
          echo ::set-output name=downloads::$(pwd)/${downloads_path}
          echo ::set-output name=ccache::$(pwd)/${ccache_path}
          echo ::set-output name=package::$(pwd)/${package_path}

      - name: Update the cache (downloads)
        uses: actions/cache@v2
        with:
          path: ${{ steps.build_paths.outputs.downloads }}

          key: |
            gitmodules_${{ matrix.config.os }}_${{ matrix.llvm }}_${{ github.sha }}
          restore-keys: |
            gitmodules_${{ matrix.config.os }}_${{ matrix.llvm }}

      - name: Update the cache (ccache)
        uses: actions/cache@v2
        with:
          path: ${{ steps.build_paths.outputs.ccache }}

          key: |
            gitmodules_${{ matrix.config.os }}_${{ matrix.llvm }}_${{ github.sha }}
          restore-keys: |
            gitmodules_${{ matrix.config.os }}_${{ matrix.llvm }}

      - name: Install linux build requirements
        if: ${{ matrix.config.name == 'ubuntu' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            software-properties-common tar wget libncurses5 \
            clang-12 cmake ninja-build python3-pip ccache

      - name: Install macos build requirements
        if: ${{ matrix.config.name == 'macos' }}
        shell: bash
        run: |
          brew install ninja cmake python3 llvm@12 ccache

      - name: Clone the vast repository
        uses: actions/checkout@v3
        with:
          path: ${{ steps.build_paths.outputs.source }}/vast
          fetch-depth: 0

      - name: Install vast test requirements
        shell: bash
        run: |
          sudo pip3 install lit
          sudo ln -s /usr/bin/FileCheck-12 ${{ steps.build_paths.outputs.install }}/FileCheck

      - name: Download llvm ${{ matrix.llvm }} package
        shell: bash
        working-directory: ${{ steps.build_paths.outputs.downloads }}
        run: |
          llvm_archive="clang+llvm-${{ matrix.llvm }}-${{ matrix.config.llvm_pkg }}.tar.xz"
          llvm_url_path="https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ matrix.llvm }}/${llvm_archive}"

          if [[ ! -f "${llvm_archive}" ]] ; then
            echo "Downloading: ${llvm_url_path}"
            wget "${llvm_url_path}"
          fi

          mkdir "${{ steps.build_paths.outputs.install }}/llvm"
          tar -xf "${llvm_archive}" -C "${{ steps.build_paths.outputs.install }}/llvm" --strip-components=1

      - name: Set compilers
        id: envvars
        run: |
          if [[ "${{matrix.config.name }}" == "macos" ]]; then
            echo "::set-output name=cc::/usr/local/opt/llvm@12/bin/clang"
            echo "::set-output name=cxx::/usr/local/opt/llvm@12/bin/clang++"
          fi

          if [[ "${{matrix.config.name }}" == "ubuntu" ]]; then
            echo "::set-output name=cc::clang-12"
            echo "::set-output name=cxx::clang++-12"
          fi

      - name: Configure vast
        working-directory: ${{ steps.build_paths.outputs.build }}

        env:
          CCACHE_DIR: ${{ steps.build_paths.outputs.ccache }}
          VAST_INSTALL_DIR: "${{ steps.build_paths.outputs.install }}"

        run: |
          LLVM_INSTALL_DIR="${{ steps.build_paths.outputs.install }}/llvm"

          cmake -G Ninja -B ${{ steps.build_paths.outputs.build }} \
            -S ${{ steps.build_paths.outputs.source }}/vast \
            -D LLVM_EXTERNAL_LIT=/usr/local/bin/lit \
            -D LLVM_INSTALL_DIR=${LLVM_INSTALL_DIR} \
            -D ENABLE_TESTING=ON \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_VERBOSE_MAKEFILE=True \
            -D SYSTEM_NAME="${{ matrix.config.arch }}-${{ matrix.config.os }}" \
            -D CMAKE_C_COMPILER=${{ steps.envvars.outputs.cc }} \
            -D CMAKE_CXX_COMPILER=${{ steps.envvars.outputs.cxx }}

      - name: Build vast
        working-directory: ${{ steps.build_paths.outputs.build }}

        env:
          CCACHE_DIR: ${{ steps.build_paths.outputs.ccache}}

        run: |
          cmake --build .

      - name: Run lit tests
        working-directory: ${{ steps.build_paths.outputs.build }}

        run: |
          export PATH="${{ steps.build_paths.outputs.install }}:$PATH"
          cmake --build . --target check-vast

      - name: Package vast
        working-directory: ${{ steps.build_paths.outputs.build }}
        run: |
          cpack -G TXZ --config ./CPackConfig.cmake

      - name: Extract package
        working-directory: ${{ steps.build_paths.outputs.install }}
        run: |
          mkdir vast
          tar -xf ${{ steps.build_paths.outputs.build }}/package/*.tar.xz -C vast --strip-components=1

      - name: Test codegen example
        working-directory: ${{ steps.build_paths.outputs.source }}/vast/example/codegen

        run: |
          LLVM_INSTALL_DIR="${{ steps.build_paths.outputs.install }}/llvm"

          cmake -G Ninja -B build -S . \
            -D LLVM_INSTALL_DIR=${LLVM_INSTALL_DIR} \
            -D VAST_INSTALL_DIR=${{ steps.build_paths.outputs.install }}/vast \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_VERBOSE_MAKEFILE=True \
            -D CMAKE_C_COMPILER=${{ steps.envvars.outputs.cc }} \
            -D CMAKE_CXX_COMPILER=${{ steps.envvars.outputs.cxx }}

          cmake --build build

      - name: Upload vast package artifact
        uses: actions/upload-artifact@v3
        with:
          name: vast-${{ matrix.config.arch }}-${{ matrix.config.os }}
          path: ${{ steps.build_paths.outputs.build }}/package/
          retention-days: 30

  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - name: Clone the vast repository
        uses: actions/checkout@v3
        with:
          path: ./vast
          fetch-depth: 0

      - name: "Download build artifacts"
        id: download
        uses: actions/download-artifact@v3

      - name: Setup the build paths
        shell: bash
        run: ls -R

      - name: "Publish Pre-Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./vast/LICENSE
            ${{steps.download.outputs.download-path}}/vast-*/*.tar.xz
