#
# Copyright (c) 2023, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Linters

on:
  pull_request:
    paths-ignore: "docs/**"

jobs:
  cpp-linter:
    strategy:
      matrix:
        llvm-version: [16]
        image-version: [22.04]

    runs-on: ubuntu-${{ matrix.image-version }}
    container:
      image:
        ghcr.io/trailofbits/vast-ubuntu-${{ matrix.image-version }}-llvm-${{ matrix.llvm-version }}-dev:latest

    permissions:
      actions: write
      issues: write
      pull-requests: write

    env:
        CMAKE_PREFIX_PATH: "/usr/lib/llvm-${{ matrix.llvm-version }}/lib/cmake/mlir/;/usr/lib/llvm-${{ matrix.llvm-version }}/lib/cmake/clang/"
        TOOLCHAIN: ${{ github.workspace }}/cmake/lld.toolchain.cmake

    steps:
      - name: Clone the vast repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Export compile commands
        run: cmake --preset ninja-multi-default --toolchain ${TOOLCHAIN} -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}

      - name: Run C++ Linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 16
          style: file
          database: ./builds/ninja-multi-default/
          lines-changed-only: true
          thread-comments: true
          step-summary: true
          ignore: 'test'
          tidy-checks: ''

      - name: Report result
        if: steps.linter.outputs.checks-failed > 0
        run:
          echo "Some files failed the linting checks!"
          exit 1
