#
# Copyright (c) 2023, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Linters

on:
  push:
    paths-ignore: "docs/**"
  pull_request:
    paths-ignore: "docs/**"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the vast repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Run C++ Linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 16
          style: file
          lines-changed-only: true
          thread-comments: true
          step-summary: true
