#
# Copyright (c) 2022-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: "Tag latest"

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - "master"
permissions: write-all

jobs:
  update_tag:
    strategy:
      matrix:
        image-version: [22.04]
    runs-on: ubuntu-${{ matrix.image-version }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
    - name: Clone the VAST repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: '0' # Required by the tag action

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true #prefix v to the tag
        DEFAULT_BUMP: patch